spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:your_default_db_name}
    username: ${POSTGRES_USERNAME:your_default_username}
    password: ${POSTGRES_PASSWORD:your_default_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
jwt:
  secret: ${JWT_SECRET_KEY:your_default_jwt_secret_key}
  expiration: 86400000
  
server:
  port: 8080